spring.application.name=com.rakesh-smart-task-manager
# --- Server ---
#server.port=8080                   
# --- H2 console ---
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console  

# --- Datasource (in\u2011memory) ---
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.jpa.hibernate.ddl-auto=update  

# --- Logging (optional but handy) ---
#---logging.level.org.springframework=INFO
#logging.level.com.rakesh=DEBUG    
#spring.security.user.name=rakesh
#spring.security.user.password=
#spring.datasource.url=jdbc:postgresql://localhost:5432/smart_task_manager
#spring.datasource.username=rakeshmandal
#spring.datasource.password=
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.profiles.active=dev