spring.datasource.url=jdbc:postgresql://localhost:5432/smart_task_manager
spring.datasource.username=rakeshmandal
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080